# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux-amd64:
    name: build linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.'

    - name: Install dependencies
      run: |
        go get .

    - name: Build
      run:  go build -v ./...

    - name: Test
      run: go test -v ./...

#  build-windows-amd64:
#    name: build windows/amd64
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Set up Go
#      uses: actions/setup-go@v5
#      with:
#        go-version: '1.24'
#
#    - name: Install dependencies
#      run: |
#        go get .
#
#    - name: Install GoVersionInfo
#      run: |
#        go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
#
#    - name: Generate
#      run: go generate -v ./...
#
#    - name: Build
#      run: go build -v ./...
#
#    - name: Test
#      run: go test -v ./...
